name: mypy type-checking
on:
    push:
        branches:
        - main
        - dev
    pull_request:
        branches:
        - '*'
    workflow_dispatch:
jobs:
  Type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.x
          architecture: x64
      - name: Install dependencies
        run: python -m pip install . && python -m pip uninstall --yes ryvencore
      - name: Install type-checking dependencies
        run: python -m pip install mypy --user
      - name: Typecheck
        run: mypy
